### PR TITLE
fix several small bugs

### PR DESCRIPTION
**Pull request by simonrousseau**

### CODE REVIEW

**Review by BilelJegham — CHANGES_REQUESTED** [review]
Great

Maybe had in this PR worlkflow Github Action with eslint to check code.

**Comment by simonrousseau** [comment]
@BilelJegham eslint and prettier have been added to format and uniformise codebase

**Comment by simonrousseau** [comment]
@BilelJegham All eslint errors have been fixed
Can you please merge this pull request before starting new developments ;)

**Review by BilelJegham — APPROVED** [review]
Great merge

**Pull request merged**
